insert into country (iso_code,country_name,country_capital,country_independence_date) values ('DO','República Dominicana','Santo Domingo','23/11/1986');
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('CA','Canada','Ottawa','01/07/1867');
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('EC','Ecuador','Quito','24/05/1822');
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('HT','Haití','Puerto Príncipe','01/01/1804');
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('VE','Venezuela','Caracas','05/07/1811');
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('PY','Paraguay','Asunción','15/05/1811');
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('JM','Jamaica','Kingston','06/08/1962');
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('GT','Guatemala','Ciudad de Guatemala','15/09/1821');
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('CR','Costa Rica','San José','15/07/1821');
insert into country (iso_code,country_name,country_capital,country_independence_date) values ('BO','Bolivia','Sucre','06/08/1825');